services:
  demo:
    image: demo
    build:
      context: .
      dockerfile: src/Demo/Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - ./src:/app
  
  elasticsearch:
    image: elasticsearch:7.17.10
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.5.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch