# This is a generated file. Not intended for manual editing.
services:
  demo:
    build:
      context: "C:\\Users\\mohamed samir\\RiderProjects\\Demo-Elastic"
      dockerfile: "src/Demo/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app-1/bin/Debug/net8.0/Demo.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "demo:dev"
    ports: []
    volumes:
    - "C:\\Users\\mohamed samir\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\mohamed samir\\RiderProjects\\Demo-Elastic\\src\\Demo:/app-1:rw"
    - "C:\\Users\\mohamed samir\\RiderProjects\\Demo-Elastic:/src:rw"
    working_dir: "/app-1"
